version: '3.1'
services:
   webserver:
     image: nginx:alpine
     container_name: webserver
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
   database:
     image: mysql:5.7
     container_name: Mysqldb
     restart: unless-stopped
     volumes:
       - 'db_data:/var/lib/mysql'
     ports:
       - "3306:3306"
     environment:
       MYSQL_DATABASE: admin
       MYSQL_ROOT_PASSWORD: admin       
volumes:
    db_data:
      driver: local