name: Build for Group 6 application
on: push

jobs:
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run --name db -dp 3306:3306 database
          mvn -Dtest= com.napier.coursework.AppIntegrationTest test
          docker stop db
          docker rm db
          docker image rm db
  build:
    name: Group 6 application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
#      - name: Build with Maven
#        run: mvn package
#      - name: Run docker compose
#        run: docker-compose up --abort-on-container-exit
      - name: Unit Tests
        run: mvn -Dtest=com.napier.coursework.AppTest test
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit